/* ============================================================
   gen_hexagrams.js — one-time generator for ekikyo-api/hexagrams.py

   Derives the 64-hexagram master (name / reading / upper / lower /
   summary / keywords) from the FRONTEND source of truth so the API
   can never disagree with the site:
     - content  ← ../../hexdata.js   (const HEX, keyed by King Wen no.)
     - trigrams ← ../../index.html   (TRI elements + KW reverse-lookup)

   Run from the repo root:
     node ekikyo-api/tools/gen_hexagrams.js .
   Re-run whenever hexdata.js changes; commit the generated .py.
   ============================================================ */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(process.argv[2] || '.');
const src = fs.readFileSync(path.join(ROOT, 'hexdata.js'), 'utf8');

// hexdata.js declares `const HEX = {...}` and `const LINES_FOR = {...}` with no
// export — evaluate it in a throwaway function scope and hand both back out.
// LINES_FOR[n] = the 6 line bits (bottom→top) and lets us name each 爻 (初九 …).
const _ev = (new Function(src + '\n;return {HEX: (typeof HEX!=="undefined")?HEX:null, LINES_FOR: (typeof LINES_FOR!=="undefined")?LINES_FOR:null};'))();
const HEX = _ev.HEX, LINES_FOR = _ev.LINES_FOR;
if (!HEX) { console.error('HEX not found in hexdata.js'); process.exit(1); }

// 爻の呼び名を位置(下=0…上=5)と陰陽(1=陽→九／0=陰→六)から組む。frontend yaoName と同一規則。
function yaoName(i, val) {
  const yy = (val === 1) ? '九' : '六';
  if (i === 0) return '初' + yy;
  if (i === 5) return '上' + yy;
  return yy + ['二', '三', '四', '五'][i - 1];
}

// Trigram table — index order matches index.html TRI (乾兌離震巽坎艮坤).
const TRI = [
  { k: '乾', e: '天' }, { k: '兌', e: '澤' }, { k: '離', e: '火' }, { k: '震', e: '雷' },
  { k: '巽', e: '風' }, { k: '坎', e: '水' }, { k: '艮', e: '山' }, { k: '坤', e: '地' },
];
// KW[lowerIdx][upperIdx] -> King Wen number (verbatim from index.html).
const KW = [
  [1, 43, 14, 34, 9, 5, 26, 11],
  [10, 58, 38, 54, 61, 60, 41, 19],
  [13, 49, 30, 55, 37, 63, 22, 36],
  [25, 17, 21, 51, 42, 3, 27, 24],
  [44, 28, 50, 32, 57, 48, 18, 46],
  [6, 47, 64, 40, 59, 29, 4, 7],
  [33, 31, 56, 62, 53, 39, 52, 15],
  [12, 45, 35, 16, 20, 8, 23, 2],
];

// Invert KW: number -> { lower, upper } trigram kanji.
const tri = {};
for (let li = 0; li < 8; li++) {
  for (let ui = 0; ui < 8; ui++) {
    tri[KW[li][ui]] = { lower: TRI[li].k, upper: TRI[ui].k };
  }
}

const pyStr = (s) => '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
// 爻辞オブジェクト1件を Python dict リテラルに。AIには name/text(原文)/meaning(正規の意味)だけ渡す
// （静的助言 advice は AI が自前で書くので転記しない）。
const pyYao = (o) => '{"name": ' + pyStr(o.name) + ', "text": ' + pyStr(o.text) + ', "meaning": ' + pyStr(o.meaning) + '}';

const out = [];
out.push('# -*- coding: utf-8 -*-');
out.push('# AUTO-GENERATED by tools/gen_hexagrams.js from ../hexdata.js + index.html (TRI/KW).');
out.push('# Do not edit by hand — regenerate so this stays consistent with the frontend.');
out.push('# name -> {num, reading, upper, lower, summary, keywords[, lines, yong]}');
out.push('#   lines/yong (爻辞) appear only for hexagrams that have them in hexdata.js;');
out.push('#   each = {name(初九…), text(原文), meaning(正規の意味)}. The AI reads the moving');
out.push('#   line\'s 爻辞 in light of the question; this stays the single source via hexdata.js.');
out.push('');
out.push('HEXAGRAMS = {');
for (let n = 1; n <= 64; n++) {
  const h = HEX[n];
  const t = tri[n];
  if (!h) { console.error('missing HEX entry', n); process.exit(1); }
  if (!t) { console.error('missing trigram mapping for', n); process.exit(1); }
  const kws = '[' + (h.keywords || []).map(pyStr).join(', ') + ']';
  let entry =
    `    ${pyStr(h.name)}: {"num": ${h.num}, "reading": ${pyStr(h.reading)}, ` +
    `"upper": ${pyStr(t.upper)}, "lower": ${pyStr(t.lower)}, ` +
    `"summary": ${pyStr(h.summary)}, "keywords": ${kws}`;
  // 爻辞（任意）。LINES_FOR[n] の陰陽から 爻名 を確定して埋め込む。
  if (Array.isArray(h.lines)) {
    const bits = LINES_FOR && LINES_FOR[n];
    if (!bits) { console.error('LINES_FOR missing for', n, '(needed to name 爻)'); process.exit(1); }
    const items = h.lines.map((ln, i) => pyYao({ name: yaoName(i, bits[i]), text: ln.text, meaning: ln.meaning }));
    entry += `, "lines": [${items.join(', ')}]`;
  }
  if (h.yong) {
    // 名前が無ければ陰陽から導く（全陽=用九／全陰=用六）。'用九' 固定だと用六を取り違える。
    const yb = LINES_FOR && LINES_FOR[n];
    const yongName = h.yong.name || (yb && yb.every((b) => b === 1) ? '用九' : '用六');
    entry += `, "yong": ${pyYao({ name: yongName, text: h.yong.text, meaning: h.yong.meaning })}`;
  }
  entry += '},';
  out.push(entry);
}
out.push('}');
out.push('');

const dest = path.join(ROOT, 'ekikyo-api', 'hexagrams.py');
fs.writeFileSync(dest, out.join('\n'), 'utf8');

console.log('wrote', dest, 'with', Object.keys(HEX).length, 'entries');
console.log('sanity  #1:', HEX[1].name, tri[1], '| #3:', HEX[3].name, tri[3], '| #64:', HEX[64].name, tri[64]);
