/* ============================================================
   gen_hexagrams.js — one-time generator for ekikyo-api/hexagrams.py

   Derives the 64-hexagram master (name / reading / upper / lower /
   summary / keywords) from the FRONTEND source of truth so the API
   can never disagree with the site:
     - content  ← ../../hexdata.js   (const HEX, keyed by King Wen no.)
     - trigrams ← ../../index.html   (TRI elements + KW reverse-lookup)

   Run from the repo root:
     node ekikyo-api/tools/gen_hexagrams.js .
   Re-run whenever hexdata.js changes; commit the generated .py.
   ============================================================ */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(process.argv[2] || '.');
const src = fs.readFileSync(path.join(ROOT, 'hexdata.js'), 'utf8');

// hexdata.js declares `const HEX = {...}` with no export — evaluate it in a
// throwaway function scope and hand HEX back out.
const HEX = (new Function(src + '\n;return (typeof HEX !== "undefined") ? HEX : null;'))();
if (!HEX) { console.error('HEX not found in hexdata.js'); process.exit(1); }

// Trigram table — index order matches index.html TRI (乾兌離震巽坎艮坤).
const TRI = [
  { k: '乾', e: '天' }, { k: '兌', e: '澤' }, { k: '離', e: '火' }, { k: '震', e: '雷' },
  { k: '巽', e: '風' }, { k: '坎', e: '水' }, { k: '艮', e: '山' }, { k: '坤', e: '地' },
];
// KW[lowerIdx][upperIdx] -> King Wen number (verbatim from index.html).
const KW = [
  [1, 43, 14, 34, 9, 5, 26, 11],
  [10, 58, 38, 54, 61, 60, 41, 19],
  [13, 49, 30, 55, 37, 63, 22, 36],
  [25, 17, 21, 51, 42, 3, 27, 24],
  [44, 28, 50, 32, 57, 48, 18, 46],
  [6, 47, 64, 40, 59, 29, 4, 7],
  [33, 31, 56, 62, 53, 39, 52, 15],
  [12, 45, 35, 16, 20, 8, 23, 2],
];

// Invert KW: number -> { lower, upper } trigram kanji.
const tri = {};
for (let li = 0; li < 8; li++) {
  for (let ui = 0; ui < 8; ui++) {
    tri[KW[li][ui]] = { lower: TRI[li].k, upper: TRI[ui].k };
  }
}

const pyStr = (s) => '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';

const out = [];
out.push('# -*- coding: utf-8 -*-');
out.push('# AUTO-GENERATED by tools/gen_hexagrams.js from ../hexdata.js + index.html (TRI/KW).');
out.push('# Do not edit by hand — regenerate so this stays consistent with the frontend.');
out.push('# name -> {num, reading, upper, lower, summary, keywords}');
out.push('');
out.push('HEXAGRAMS = {');
for (let n = 1; n <= 64; n++) {
  const h = HEX[n];
  const t = tri[n];
  if (!h) { console.error('missing HEX entry', n); process.exit(1); }
  if (!t) { console.error('missing trigram mapping for', n); process.exit(1); }
  const kws = '[' + (h.keywords || []).map(pyStr).join(', ') + ']';
  out.push(
    `    ${pyStr(h.name)}: {"num": ${h.num}, "reading": ${pyStr(h.reading)}, ` +
    `"upper": ${pyStr(t.upper)}, "lower": ${pyStr(t.lower)}, ` +
    `"summary": ${pyStr(h.summary)}, "keywords": ${kws}},`
  );
}
out.push('}');
out.push('');

const dest = path.join(ROOT, 'ekikyo-api', 'hexagrams.py');
fs.writeFileSync(dest, out.join('\n'), 'utf8');

console.log('wrote', dest, 'with', Object.keys(HEX).length, 'entries');
console.log('sanity  #1:', HEX[1].name, tri[1], '| #3:', HEX[3].name, tri[3], '| #64:', HEX[64].name, tri[64]);
